"""Business logic for voice conversations (Phase 8): speech-to-text on the way
in, text-to-speech on the way out. Reuses the same StorageService abstraction
as avatar uploads — never touches the filesystem directly."""

from __future__ import annotations

import io
import logging
from uuid import UUID

from fastapi import UploadFile

from app.core.audio_validation import validate_audio_upload
from app.core.exceptions import MessageAudioNotFoundError
from app.models.conversation_message import ConversationMessage
from app.models.conversation_session import ConversationSession
from app.models.message_audio import AUDIO_SOURCE_GENERATED, AUDIO_SOURCE_INPUT, MessageAudio
from app.repositories.message_audio_repository import MessageAudioRepository
from app.services.storage import StorageService
from app.services.voice.base import SpeechToTextProvider, TextToSpeechProvider
from app.services.voice.factory import get_speech_to_text_provider, get_text_to_speech_provider

logger = logging.getLogger(__name__)

_VOICE_SUBDIRECTORY = "voice"


class _InMemoryUploadFile:
    """
    Minimal UploadFile-compatible wrapper (exposes .filename, .content_type,
    .file) so StorageService.save() can persist provider-generated bytes
    (e.g. TTS output) without any change to its interface. Deliberately not a
    real Starlette UploadFile — avoids depending on its constructor signature,
    which differs across Starlette versions.
    """

    def __init__(self, data: bytes, *, filename: str, content_type: str) -> None:
        self.filename = filename
        self.content_type = content_type
        self.file = io.BytesIO(data)


class VoiceService:
    def __init__(
        self,
        message_audio_repository: MessageAudioRepository,
        storage_service: StorageService,
        stt_provider: SpeechToTextProvider | None = None,
        tts_provider: TextToSpeechProvider | None = None,
    ) -> None:
        self.message_audio_repository = message_audio_repository
        self.storage_service = storage_service
        self.stt_provider = stt_provider or get_speech_to_text_provider()
        self.tts_provider = tts_provider or get_text_to_speech_provider()

    def transcribe_upload(self, file: UploadFile) -> str:
        """
        Validate and transcribe an uploaded audio file to text.

        This is an explicit user action — validation and AI failures are
        allowed to propagate (AIConfigurationError / AIProviderError /
        audio validation errors) so the caller gets a real error, not a
        silent empty transcript.
        """
        validate_audio_upload(file)

        audio_bytes = file.file.read()
        file.file.seek(0)  # rewind so store_input_audio() can re-read the same upload

        result = self.stt_provider.transcribe(
            audio_bytes=audio_bytes,
            filename=file.filename or "audio",
            content_type=file.content_type or "application/octet-stream",
        )
        return result.text

    def store_input_audio(
        self,
        session: ConversationSession,
        user_message: ConversationMessage,
        file: UploadFile,
    ) -> MessageAudio | None:
        """
        Persist the learner's original recording. Best-effort — the
        transcript/AI-reply flow has already succeeded by the time this
        runs, so a storage hiccup here is logged and swallowed rather than
        failing the whole request.
        """
        try:
            audio_url = self.storage_service.save(
                file,
                filename_prefix=str(user_message.id),
                subdirectory=_VOICE_SUBDIRECTORY,
            )
            return self.message_audio_repository.add(
                message_id=user_message.id,
                session_id=session.id,
                source=AUDIO_SOURCE_INPUT,
                audio_url=audio_url,
                mime_type=file.content_type or "application/octet-stream",
            )
        except Exception as exc:  # noqa: BLE001 - storing the input recording must never break the flow
            logger.warning(
                "Failed to store input audio session_id=%s message_id=%s error=%s",
                session.id,
                user_message.id,
                exc,
            )
            return None

    def synthesize_reply_audio(
        self,
        session: ConversationSession,
        assistant_message: ConversationMessage,
    ) -> MessageAudio | None:
        """
        Best-effort: synthesize and store TTS audio for the AI's reply.
        Never raises — a TTS provider hiccup must not break the voice
        message response, same resilience pattern as live coaching feedback.
        """
        try:
            audio_bytes = self.tts_provider.synthesize(assistant_message.content)
            audio_file = _InMemoryUploadFile(
                audio_bytes,
                filename=f"{assistant_message.id}.mp3",
                content_type="audio/mpeg",
            )
            audio_url = self.storage_service.save(
                audio_file,
                filename_prefix=str(assistant_message.id),
                subdirectory=_VOICE_SUBDIRECTORY,
            )
            return self.message_audio_repository.add(
                message_id=assistant_message.id,
                session_id=session.id,
                source=AUDIO_SOURCE_GENERATED,
                audio_url=audio_url,
                mime_type="audio/mpeg",
            )
        except Exception as exc:  # noqa: BLE001 - TTS must never break the chat flow
            logger.warning(
                "Failed to synthesize reply audio session_id=%s message_id=%s error=%s",
                session.id,
                assistant_message.id,
                exc,
            )
            return None

    def get_audio_for_message(self, message_id: UUID, session_id: UUID) -> MessageAudio:
        audio = self.message_audio_repository.get_by_message_id(message_id)
        if audio is None or audio.session_id != session_id:
            raise MessageAudioNotFoundError()
        return audio